Merge static libs and bump version 2.2-3
wpilibsuite/thirdparty-ceres pull request #8
Opened 2024-11-16 01:26 UTC by ElliotScher

WPIcal had linker errors related to the Ceres dependency.

2024-12-01 04:34 UTC, Gold856 requested changes

2024-12-01 04:34 UTC, Gold856 commented on publish.gradle
> +            inputFiles = ["ceres.lib", "gflags.lib", "GKlib.lib", "glog.lib", "lapack.lib", "libamd.lib", "libbtf.lib", "libcamd.lib", "libccolamd.lib", "libcholmod.lib", "libcolamd.lib", "libcxspars
```suggestion
            inputFiles = inputFiles + "libf2c.lib"
```

2024-12-01 04:34 UTC, Gold856 commented on publish.gradle
> +            inputFiles = ["ceres-debug.lib", "gflags_debug.lib", "GKlib.lib", "glog.lib", "lapack.lib", "libamdd.lib", "libbtfd.lib", "libcamdd.lib", "libccolamdd.lib", "libcholmodd.lib", "libcolamdd
```suggestion
            inputFiles = inputFiles + "libf2c.lib"
```

2024-12-03 05:58 UTC, Gold856 requested changes
#9 will be changing how the x86 Windows libraries are built to match ARM Windows. As far I can tell, the only changes you need to make are including libf2c into the base inputFiles array and using `gflags_static` and `gflags_static_debug` instead of just `gflags` and `gflags_debug`.

Also, consider specifying the file extension when you iterate over inputFiles instead of specifying it for all the individual libraries. I think it's more readable with less file extensions.

2024-12-03 05:58 UTC, Gold856 commented on publish.gradle
> +def pubVersion = "2.2-3"
```suggestion
def pubVersion = "$ext.version-3"
```

2024-12-03 06:18 UTC, ElliotScher commented
are ```gflags_static``` and ```gflags_static_debug``` the libs for windows? on my linux machine they are ```gflags``` and ```gflags_debug```

2024-12-03 06:25 UTC, Gold856 commented
Yes.
![image](https://github.com/user-attachments/assets/b99e9411-e4aa-4ffc-ab55-596cde2b5ab1)

2024-12-04 03:54 UTC, merged